project:
  type: website
  output-dir: _site

website:
  title: "Pattern Recognition 2025-Scientific Blog"
  navbar:
    background: "#ff69b4"
    foreground: "#ffffff"

format:
  html:
    toc: false
    self-contained: true
    code-tools: true
    code-fold: true

execute:
  freeze: auto

